#------------------------------------------------------------------
# Запуск двух серверов AWS EC2 по шаблону
# 
#------------------------------------------------------------------

name: EC2-Launch
env:
  TEMPLATE_ID      : "lt-0083ac67d8006e1a5"
  TEMPLATE_VERSION : "1"

# Запускаем по событию. 
on:
  # Ручками в Actions вкладке
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Задача: Запуск серверов
  AWS-launch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Используем настроенную среду
    environment:
      name: My_AWS
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Аутентификация
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : "eu-central-1"
          
      # Запуск и получение id первого EC2 сервера
      - name: Launch instance 1
        run: |
          aws ec2 run-instances --launch-template LaunchTemplateId=${{ env.TEMPLATE_ID }},Version=${{ env.TEMPLATE_VERSION }} > instance1.json
          echo 'INSTANCE_ID1<<EOF' >> $GITHUB_ENV
          cat instance1.json | grep "\"i-" | awk {'print $2'} |tr -d , |tr -d \" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      # Запуск и получение id второго EC2 сервера
      - name: Launch instance 2
        run: |
          aws ec2 run-instances --launch-template LaunchTemplateId=${{ env.TEMPLATE_ID }},Version=${{ env.TEMPLATE_VERSION }} > instance2.json
          echo 'INSTANCE_ID2<<EOF' >> $GITHUB_ENV
          cat instance2.json | grep "\"i-" | awk {'print $2'} |tr -d , |tr -d \" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Print instance id
        run: echo "${{ env.INSTANCE_ID1 }} + ${{ env.INSTANCE_ID2 }}"
    
#EOF                  
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
