#------------------------------------------------------------------
# Осваиваю GitHub Actions в связке AWS EC2
# 
#------------------------------------------------------------------

name: EC2-Describe

# Запускаем по событию. 
on:
  # Ручками в Actions вкладке
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Выведем информацию об имеющихся серверах
  AWS-describe:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Используем настроенную среду
    environment:
      name: My_AWS
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Аутентификация
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : "eu-central-1"
          
      # Вывод информации об EC2 серверах
      - name: Describe instances
        run: aws ec2 describe-instances
    
#EOF                  
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
