#------------------------------------------------------------------
# Работа с AWS EC2 с помощью python boto3
#------------------------------------------------------------------

name: Testing python scripts
    
# Запускаем по событию. 
on:
  # Ручками в Actions вкладке
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Задача: Запуск python-скрипта
  Python-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Используем настроенную среду
    environment:
      name: My_AWS
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
      
      # Аутентификация
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region             : "eu-central-1"
          
      # Запуск и получение id первого EC2 сервера
      - name: Testing script
        run: |
          python testing.py                  
      
#EOF    
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
